version: '3'

services:
  next-js-boilerplate:
    image: next-js-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 14.15.4
        PORT: 8080
    env_file:
      - .env.development
      - .env.production
    volumes:
    - ./keys:/usr/src/app/keys:ro
    - .env-development:/usr/src/app/.env-development:ro
    - .env-local:/usr/src/app/.env-local:ro
    - .env-production:/usr/src/app/.env-production:ro
    ports:
      - "8080:8080"
